apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-config
  namespace: argocd
  annotations:
    # Sync Wave -5 ensures this syncs before standard apps (wave 0)
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/odev-swe/homelab-from-hell.git
    targetRevision: main
    path: kubernetes/argocd/config/storageclass
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
