apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: hashicorp-vault
spec:
  interval: 24h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hashicorp-vault
  namespace: hashicorp-vault
spec:
  suspend: false
  interval: 30m
  chart:
    spec:
      chart: vault
      version: "0.32.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: hashicorp-vault
      interval: 12h
  values:
    server:
      extraEnvironmentVars:
        AWS_REGION: "ap-southeast-5"
        
      extraSecretEnvironmentVars:
        - envName: AWS_ACCESS_KEY_ID
          secretName: vault-aws-kms
          secretKey: AWS_ACCESS_KEY_ID
        - envName: AWS_SECRET_ACCESS_KEY
          secretName: vault-aws-kms
          secretKey: AWS_SECRET_ACCESS_KEY
      
      ha:
        enabled: true
        replicas: 2

        config: |
          ui = true

          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "consul" {
            path = "vault"
            address = "HOST_IP:8500"
          }

          seal "awskms" {
            region = "ap-southeast-5"
            kms_key_id = "19ab179d-773d-4d1d-ba69-022b0fea9ec4"
          }

          service_registration "kubernetes" {}

        raft:
          enabled: true
          setNodeId: true

      dataStorage:
        enabled: true
        size: 10Gi
        storageClass: nfs-vault-csi

      auditStorage:
        enabled: true
        size: 10Gi
        storageClass: nfs-vault-csi